### ISSUE TITLE
Update disaster recovery documentation

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/tenant-security-client-nodejs#103]
Add information on recovering tenant secrets, with a concrete example.
Link to documentation on document header formats in ironcore-documents.

**Comment by skeet70** [comment]
I've created PRs to add deterministic info including recovering secrets to the Node disaster docs and links to it from the website.

I didn't add ironcore alloy / doc v5 information, but I did mention that `ironcore-documents` is the most up-to-date source to find out about document and protobuf structure. When we 1.0 ironcore-alloy we should add a disaster recovery example in that repository as well, and link to it from the docs pages we create for ironcore-alloy at launch.
