### ISSUE TITLE
Fix publish

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/tenant-security-client-nodejs#13]
a `yarn build --publish` fails with
```
npm ERR! 404 Not Found - PUT https://registry.yarnpkg.com/@ironcorelabs%2ftenant-security-nodejs - Not found
```

I think it should be using `registry.npmjs.org` instead - after it failed, I did the step that was in the `build.js` file (`npm publish --access public`) and it published successfully.

I might just have things set up incorrectly, but I would like to either get the documentation updated or get this resolved.

**Comment by skeet70** [comment]
We don't use yarn for publishing. Our documentation and normal release process is using the `build.js` script, which uses npm. If you want to run just a publish manually you can do as you did and run `npm publish` yourself, which should work.

If there's anything not covered by https://github.com/IronCoreLabs/tenant-security-client-nodejs/blob/master/CONTRIBUTING.md#publishing, we should re-open this with more info about the issue.
